[workspace]

members = [
    "rust/crd", "rust/operator", "rust/operator-binary"
]

[patch.'https://github.com/stackabletech/operator-rs.git']
stackable-operator = { path = "/home/sliebau/IdeaProjects/stackable/operator-rs"}