[workspace]

members = [
    "rust/crd", "rust/operator", "rust/operator-binary"
]

[patch.'https://github.com/stackabletech/operator-rs.git']
stackable-operator = {  git = 'https://github.com/stackabletech//operator-rs.git', branch =  "feat/pause-reconciliation"}
