---
apiVersion: v2
name: hdfs-operator
version: "25.11.0"
appVersion: "25.11.0"
description: The Stackable Operator for Apache HDFS
home: https://github.com/stackabletech/hdfs-operator
maintainers:
  - name: Stackable
    url: https://www.stackable.tech
