[package]
authors = ["Stackable GmbH info@stackable.de"]
description = "Stackable Operator for Apache HDFS - The Operator Library"
edition = "2021"
license = "OSL-3.0"
name = "stackable-hdfs-operator"
repository = "https://github.com/stackabletech/hdfs-operator"
version = "0.6.0-nightly"

[dependencies]
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", tag = "0.25.2" }
stackable-hdfs-crd = { path = "../crd" }

futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
strum = "0.24"
thiserror = "1.0"
tokio = { version = "1.21", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-futures = { version = "0.2", features = ["futures-03"] }
